
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatgpt:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "8085:8085"