server:
  port: 8085 

spring:
  r2dbc:
      url: ${DATABASE_URL}               # Variable de entorno para la URL de la base de datos
      username: ${DATABASE_USERNAME}     # Variable de entorno para el nombre de usuario
      password: ${DATABASE_PASSWORD}   

# sdk install java 17.0.11-jbr
# mvn clean install -DskipTests
# mvn spring-boot:run
