name: SonarCloud
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Solo descarga el último commit para acelerar el proceso

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache Maven and SonarCloud packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-cache

      - name: Build and analyze (skip tests)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          mvn -B verify -DskipTests \
            -Dsonar.projectKey=MariaAvilaConde_AS222S5_T01_be \
            -Dspring.datasource.url=$DATABASE_URL \
            -Dspring.datasource.username=$DATABASE_USERNAME \
            -Dspring.datasource.password=$DATABASE_PASSWORD \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up QEMU for cross-platform builds (optional)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build --file Dockerfile \
                       --tag marianayeli/botia:${{ github.sha }} .

      # Push the Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag marianayeli/botia:${{ github.sha }} marianayeli/botia:latest
          docker push marianayeli/botia:${{ github.sha }}
          docker push marianayeli/botia:latest
