name: SonarCloud
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Clona el repo, sin opciones extra, más ligero

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17  # Configura JDK sin configuraciones extra

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build and analyze (skip tests)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify -DskipTests \
            -Dsonar.projectKey=MariaAvilaConde_AS222S5_T01_be \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
#hola
